"""worker pins and web punch links

Revision ID: 9b5611f576b6
Revises: 2b322677deb7
Create Date: 2026-09-14 14:02:01.599916

Deploy safety: additive only (nullable columns, one NOT NULL with a server
default, one unique index on a column that starts all-NULL). Revisions
without the PIN feature never touch these columns, so traffic rollback
stays safe. Existing workers have no PIN until one is issued
(`flask admin issue-pins`); accepted assignments get a punch token lazily.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b5611f576b6'
down_revision = '2b322677deb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('pin_set_at_utc', sa.DateTime(), nullable=True))

    with op.batch_alter_table('shift_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_source', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('check_out_source', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('punch_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('pin_failed_attempts', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('pin_locked_until_utc', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_shift_assignments_punch_token'), ['punch_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_assignments_punch_token'))
        batch_op.drop_column('pin_locked_until_utc')
        batch_op.drop_column('pin_failed_attempts')
        batch_op.drop_column('punch_token')
        batch_op.drop_column('check_out_source')
        batch_op.drop_column('check_in_source')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('pin_set_at_utc')
        batch_op.drop_column('pin_hash')

    # ### end Alembic commands ###
