"""initial schema

Revision ID: 9fa0580e546d
Revises: 
Create Date: 2026-07-16 16:37:58.555476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fa0580e546d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_phone_number'), ['phone_number'], unique=True)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('location_address', sa.String(length=255), nullable=False),
    sa.Column('default_headcount', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('required_headcount', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('understaffed_alert_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.create_index('ix_shifts_job_date', ['job_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_shifts_job_id'), ['job_id'], unique=False)

    op.create_table('shift_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'cancelled', 'rejected', name='assignmentstatus'), server_default='pending', nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('reminder_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shift_id', 'employee_id', name='uq_shift_employee')
    )
    with op.batch_alter_table('shift_assignments', schema=None) as batch_op:
        batch_op.create_index('ix_assignments_shift_status', ['shift_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_assignments_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_assignments_shift_id'), ['shift_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_assignments_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # Dropping a table removes its indexes and outgoing foreign keys together.
    # MySQL rejects dropping an index that still supports a foreign key.
    op.drop_table('shift_assignments')
    op.drop_table('shifts')
    op.drop_table('jobs')
    op.drop_table('employees')
